# Generated by Django 4.2.11 on 2024-03-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=200, unique=True, verbose_name='Quote Id')),
                ('author', models.CharField(max_length=200, verbose_name='Author')),
                ('content', models.TextField(verbose_name='Content')),
                ('tags', models.CharField(max_length=250, verbose_name='Tags')),
                ('authorSlug', models.SlugField(max_length=250, verbose_name='Author Slug')),
                ('length', models.IntegerField(verbose_name='Length')),
                ('dateAdded', models.DateField(verbose_name='Date Added')),
                ('dateModified', models.DateField(verbose_name='Date Modified')),
            ],
        ),
    ]
